config/routes.rb
Boxify::Application.routes.draw do

	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # get "home/index"

  #match 'auth/:provider/callback', to: 'sessions#create'

  authenticated :user do
    root :to => "boxes#index"
  end

  root :to => "home#index"


  resources :boxes do
    member do
      post 'purchase'
    end
  end
  resources :subscriptions
end

app/models/box.rb
# == Schema Information
#
# Table name: boxes
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  name        :string(255)
#  description :string(255)
#  frequency   :string(255)
#  ship_date   :date
#  price       :decimal(, )
#  img_lg      :string(255)
#  img_sm      :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Box < ActiveRecord::Base
  attr_accessible :user_id, :name, :description, :ship_date, :frequency, :price, :img_lg, :img_sm
  belongs_to :user, :inverse_of => :boxes
  has_many :shipments, :inverse_of => :box
  has_many :subscriptions, :inverse_of => :box

  def is_subscribed?(user)
	  user.id.in?(self.subscriptions.map(&:user_id))
  end

  def is_owner?(user)
  	user == self.user
  end

  def current_shipment
    if self.shipments.where(:has_shipped => false).last.present?
      self.shipments.where(:has_shipped => false).last
    end
  end

  def last_shipment_sent
    if self.shipments.where(:has_shipped => true).order(:created_at).reverse.last.present?
      self.shipments.where(:has_shipped => true).order(:created_at).reverse.last
    end
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_filter :current_user, :except => [:index, :show]

  def index
    @boxes = Box.all
  end
  def show
    @box = Box.find(params[:id])
  end
  def new
    @box = Box.new
  end
  def create
    box = Box.create(params[:box])
    box.user = current_user
    box.save
    redirect_to box
  end
  def edit
    @box = Box.find(params[:id])
  end
  def update
    box = Box.find(params[:id])
    if box.user == @current_user
      box.update_attributes(params[:box])
    end
    redirect_to box
  end
  def destroy
  end
  def purchase
    box = Box.find(params[:id])

    begin
      if current_user.cc_id.nil?
        customer = Stripe::Customer.create(email: current_user.email, card: params[:token])
        current_user.cc_id = customer.id
        current_user.save
      end
      Stripe::Charge.create(customer: current_user.cc_id, amount: (box.price * 100).to_i, description: box.name, currency: 'usd')
      subscription = Subscription.create
      subscription.box = box
      subscription.user = current_user
      subscription.save
    rescue Stripe::CardError => @error
    end

    # if @error.nil?
    #   #Notifications.purchased_product(@auth, product).deliver
    #   # result = Result.create(:user_id => current_user.id, :box_id => box.id)
    #   box.purchase(current_user)
    # end

    @boxes = Box.all
  end
end

app/views/boxes/_anonymous.html.haml
%script{:src => "https://checkout.stripe.com/v2/checkout.js",
        :class => "stripe-button",
        :'data-label' => 'Subscribe',
        :'data-amount' => box.price * 100,
        :'data-key' => Rails.configuration.stripe[:publishable_key]}
= form_tag purchase_box_path(box), :remote => true do end

app/views/boxes/_box.html.haml
.row
  .columns.large-12
    %table
      %tr
        %th Box Name
        %th Box Creator
        %th Price
        %th Subscribed
        %th Next Shipping Date
        %tr
          %td= link_to(@box.name, @box)
          %td= @box.user.email
          %td= @box.price
          %td
            - if !@box.is_owner?(current_user)
              - if !@box.is_subscribed?(current_user)
                - if !current_user.cc_id.present?
                  = render(:partial => 'boxes/anonymous', :locals => {:box => @box})
                  / = link_to 'subscribe', new_subscription_path(box)
                - else
                  = render(:partial => 'boxes/customer', :locals => {:box => @box})
              - else
                = link_to 'unsubscribe', edit_subscription_path(box), :class => 'button small alert'
          %td= @box.ship_date

#items
  .row
    .columns.large-12
      #masonry-container.transitions-enabled.infinite-scroll.clearfix
        #items_index
          - Shipment.last.items.each do |item|
            .box
              .box-image= image_tag(item.img, :width => '100')
              / = raise 'foo'
              = item.name
              = item.description

app/views/boxes/_boxes.html.haml
.row
  .columns.large-12
    #masonry-container.transitions-enabled.infinite-scroll.clearfix
      #boxes_index
        - @boxes.each do |box|
          .box
            .box-image= link_to(image_tag(box.img_lg, :width => '100'), box)
            / = raise 'foo'
            = box.name
            = box.price
            - if !box.is_owner?(current_user)
              - if !box.is_subscribed?(current_user)
                - if !current_user.cc_id.present?
                  = render(:partial => 'boxes/anonymous', :locals => {:box => box})
                  / = link_to 'subscribe', new_subscription_path(box)
                - else
                  = render(:partial => 'boxes/customer', :locals => {:box => box})
              - else
                = link_to 'unsubscribe', edit_subscription_path(box), :class => 'button small alert'

app/views/boxes/_customer.html.haml
= form_tag purchase_box_path(box), :remote => true do
  = submit_tag 'Subscribe', :class => 'button radius'

app/views/boxes/_form.html.haml
= form_for @box do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.label :ship_date
  = f.date_select :ship_date, :order => [:day, :month, :year]
  = f.label :frequency
  = f.select :frequency, [['weekly', 'Weekly'], ['biweekly', 'Biweekly'], ['monthly', 'Monthly']]
  = f.label :price
  = f.submit

app/views/boxes/edit.html.haml
= render :partial => 'boxes/form'

app/views/boxes/index.html.haml
#boxes
  = render :partial => 'boxes/boxes'

app/views/boxes/new.html.haml
= render :partial => 'boxes/form'

app/views/boxes/purchase.js.erb
$('#boxes').empty().append('<%=j render 'boxes/boxes' %>');

app/views/boxes/show.html.haml
= render(:partial => 'boxes/box', :locals => {:box => @box})